name: Convert CSV to JSON
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  convert_csv_to_json:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository to the runner
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: python convert_csv_to_json.py
